// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import {
  type BetterAuthOptionsWithoutDatabase,
  defineAuth as baseDefineAuth,
  createAuthRuntime,
  type GenericAuthDefinition,
  getGeneratedAuthDisabledReason,
  resolveGeneratedAuthDefinition,
} from "better-convex/auth";
import { createOrm, type GenericOrmCtx, type OrmFunctions } from 'better-convex/orm';
import { initCRPC as baseInitCRPC } from 'better-convex/server';
import { internal } from './_generated/api.js';
import type { DataModel } from './_generated/dataModel';
import type {
  ActionCtx as ServerActionCtx,
  MutationCtx as ServerMutationCtx,
  QueryCtx as ServerQueryCtx,
} from './_generated/server';
import { internalMutation } from './_generated/server';
import * as authDefinitionModule from './auth';
import schema, { relations } from './schema';

const ormFunctions = (internal as unknown as Record<string, OrmFunctions>).generated;

export const orm = createOrm({
  schema: relations,
  ormFunctions,
  internalMutation,
});

export type OrmCtx<Ctx extends ServerQueryCtx | ServerMutationCtx = ServerQueryCtx> = GenericOrmCtx<Ctx, typeof relations>;
export type QueryCtx = OrmCtx<ServerQueryCtx>;
export type MutationCtx = OrmCtx<ServerMutationCtx>;
export type GenericCtx = QueryCtx | MutationCtx | ServerActionCtx;

export function withOrm<Ctx extends ServerQueryCtx | ServerMutationCtx>(ctx: Ctx) {
  return orm.with(ctx) as OrmCtx<Ctx>;
}

export const initCRPC = baseInitCRPC.dataModel<DataModel>().context({
  query: (ctx) => withOrm(ctx),
  mutation: (ctx) => withOrm(ctx),
});

export const { scheduledMutationBatch, scheduledDelete } = orm.api();
export function defineAuth<
  AuthOptions extends BetterAuthOptionsWithoutDatabase = BetterAuthOptionsWithoutDatabase,
>(
  definition: GenericAuthDefinition<GenericCtx, DataModel, typeof schema, AuthOptions>
) {
  return baseDefineAuth(definition);
}

type AuthDefinitionFromFile = Extract<
  typeof authDefinitionModule extends { default: infer T } ? T : never,
  (...args: unknown[]) => unknown
>;

const authDefinition = ((ctx: GenericCtx) =>
  resolveGeneratedAuthDefinition<AuthDefinitionFromFile>(
    authDefinitionModule,
    getGeneratedAuthDisabledReason("default_export_unavailable")
  )(ctx)) as AuthDefinitionFromFile;


const authRuntime = createAuthRuntime<
  DataModel,
  typeof schema,
  MutationCtx,
  GenericCtx,
  ReturnType<AuthDefinitionFromFile>
>({
  internal,
  moduleName: "generated",
  schema,
  auth: authDefinition,
  context: withOrm,
});

export const {
  authEnabled,
  authClient,
  getAuth,
  auth,
  create,
  deleteMany,
  deleteOne,
  findMany,
  findOne,
  updateMany,
  updateOne,
  getLatestJwks,
  rotateKeys,
  beforeCreate,
  beforeDelete,
  beforeUpdate,
  onCreate,
  onDelete,
  onUpdate,
} = authRuntime;

