// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  messages: {
    create: createApiLeaf<"mutation", typeof import("../functions/messages").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/messages").create>("messages:create"), { type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/messages").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/messages").list>("messages:list"), { type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
