import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { parse } from 'dotenv';
import { getConvexConfig } from './codegen.js';
import {
  formatConvexCommandFailure,
  runLocalConvexCommand,
} from './convex-command.js';
import { logger } from './utils/logger.js';

export interface PushOptions {
  authSyncMode?: 'auto' | 'prepare' | 'complete' | 'skip';
  commandEnv?: Record<string, string | undefined>;
  force?: boolean;
  fromFilePath?: string;
  rotate?: boolean;
  sharedDir?: string;
  silent?: boolean;
  sourceContent?: string;
  targetArgs?: string[];
}

export interface PullOptions {
  commandEnv?: Record<string, string | undefined>;
  outFilePath?: string;
  targetArgs?: string[];
}

type CommandResult = {
  exitCode: number;
  stderr: string;
  stdout: string;
};

type RunCommand = (
  args: string[],
  cwd: string,
  env?: Record<string, string | undefined>
) => Promise<CommandResult>;

type PushEnvDeps = {
  runCommand?: RunCommand;
  secretGenerator?: () => string;
};

type PullEnvDeps = {
  runCommand?: RunCommand;
};

type AuthEnvState = {
  definitionPath: string;
  generatedPath: string;
  installed: boolean;
  runtimeReady: boolean;
};

export const GENERATED_AUTH_SECRET_COMMENT = '# Generated by kitcn env push';
const AUTH_JWKS_FUNCTION = 'generated/auth:getLatestJwks';
const AUTH_ROTATE_KEYS_FUNCTION = 'generated/auth:rotateKeys';
const SIMPLE_ENV_VALUE_RE = /^[A-Za-z0-9_./:-]+$/;
const CONVEX_MANAGED_ENV_KEYS = new Set([
  'CONVEX_DEPLOYMENT',
  'CONVEX_DEPLOY_KEY',
  'CONVEX_SELF_HOSTED_URL',
  'CONVEX_SELF_HOSTED_ADMIN_KEY',
  'NEXT_PUBLIC_CONVEX_URL',
  'VITE_CONVEX_URL',
]);

const defaultRunCommand: RunCommand = async (
  args: string[],
  cwd: string,
  env?: Record<string, string | undefined>
): Promise<CommandResult> => runLocalConvexCommand(args, { cwd, env });

export const generateAuthSecret = () => randomBytes(32).toString('base64url');

const defaultSecretGenerator = () => generateAuthSecret();

const normalizeRelativePath = (cwd: string, filePath: string) =>
  path.relative(cwd, filePath).replaceAll('\\', '/') || '.';

export const resolveAuthEnvState = (params: {
  cwd: string;
  sharedDir?: string;
}): AuthEnvState => {
  const { functionsDir } = getConvexConfig(params.sharedDir);
  const definitionPath = path.join(functionsDir, 'auth.ts');
  const generatedPath = path.join(functionsDir, 'generated', 'auth.ts');

  return {
    definitionPath,
    generatedPath,
    installed: fs.existsSync(definitionPath),
    runtimeReady: fs.existsSync(generatedPath),
  };
};

export const serializeEnvValue = (value: string) => {
  if (SIMPLE_ENV_VALUE_RE.test(value)) {
    return value;
  }
  if (value.includes('\n') || value.includes('\r')) {
    return JSON.stringify(value);
  }
  return `'${value}'`;
};

const serializeEnvEntries = (entries: Record<string, string>) =>
  Object.entries(entries)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${serializeEnvValue(value)}`)
    .join('\n');

const parseConvexRunValue = (stdout: string) => {
  const trimmed = stdout.trim();
  if (trimmed.length === 0) {
    throw new Error('Convex run returned an empty value.');
  }
  try {
    const parsed = JSON.parse(trimmed) as unknown;
    if (typeof parsed === 'string') {
      return parsed;
    }
    return JSON.stringify(parsed);
  } catch {
    return trimmed;
  }
};

const readEnvSource = (params: { cwd: string; fromFilePath?: string }) => {
  if (!params.fromFilePath) {
    return null;
  }

  const filePath = path.resolve(params.cwd, params.fromFilePath);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Env file not found: ${params.fromFilePath}`);
  }

  const content = fs.readFileSync(filePath, 'utf8');
  return {
    content,
    path: filePath,
    vars: parse(content),
  };
};

const readLocalEnvFile = (envPath: string) => {
  if (!fs.existsSync(envPath)) {
    return {
      content: '',
      vars: {} as Record<string, string>,
    };
  }

  const content = fs.readFileSync(envPath, 'utf8');
  return {
    content,
    vars: parse(content),
  };
};

const ensureAuthSecret = (params: {
  envPath: string;
  preferredSecret?: string;
  secretGenerator: () => string;
  silent?: boolean;
}) => {
  const { content: localContent, vars: localVars } = readLocalEnvFile(
    params.envPath
  );
  if (localVars.BETTER_AUTH_SECRET) {
    return localVars.BETTER_AUTH_SECRET;
  }

  const secret = params.preferredSecret ?? params.secretGenerator();
  const nextContent = localContent.trimEnd();
  const prefix = nextContent.length > 0 ? '\n\n' : '';
  const appended = `${prefix}${GENERATED_AUTH_SECRET_COMMENT}\nBETTER_AUTH_SECRET=${serializeEnvValue(secret)}\n`;
  fs.mkdirSync(path.dirname(params.envPath), { recursive: true });
  fs.writeFileSync(params.envPath, `${nextContent}${appended}`);
  if (!params.silent) {
    logger.info('Generated BETTER_AUTH_SECRET in convex/.env');
  }
  return secret;
};

const runConvexCommand = async (
  runCommand: RunCommand,
  cwd: string,
  args: string[],
  env?: Record<string, string | undefined>
) => {
  const result = await runCommand(args, cwd, env);
  if (result.exitCode !== 0) {
    throw new Error(formatConvexCommandFailure(args, result));
  }
  return result;
};

const buildEnvSetArgs = (params: {
  envFilePath: string;
  force: boolean;
  targetArgs: string[];
}) => [
  'env',
  'set',
  '--from-file',
  params.envFilePath,
  ...(params.force ? ['--force'] : []),
  ...params.targetArgs,
];

const filterPushEnvEntries = (entries: Record<string, string>) =>
  Object.fromEntries(
    Object.entries(entries).filter(([key, value]) => {
      if (value.length === 0) {
        return false;
      }
      return !CONVEX_MANAGED_ENV_KEYS.has(key);
    })
  );

const resolvePushSource = (params: {
  allowMissingDefault?: boolean;
  cwd: string;
  envPath: string;
  fromFilePath?: string;
  sourceContent?: string;
}) => {
  if (typeof params.sourceContent === 'string') {
    return {
      content: params.sourceContent,
      vars: parse(params.sourceContent),
    };
  }

  const customSource = readEnvSource({
    cwd: params.cwd,
    fromFilePath: params.fromFilePath,
  });
  if (customSource) {
    return {
      content: customSource.content,
      vars: customSource.vars,
    };
  }

  if (!fs.existsSync(params.envPath)) {
    if (params.allowMissingDefault) {
      return {
        content: '',
        vars: {} as Record<string, string>,
      };
    }
    throw new Error('convex/.env file not found.');
  }

  return readLocalEnvFile(params.envPath);
};

const assertAuthInstalledForRotate = (params: {
  cwd: string;
  authState: AuthEnvState;
}) => {
  if (params.authState.installed) {
    return;
  }

  throw new Error(
    `Auth key rotation requires auth scaffold at ${normalizeRelativePath(params.cwd, params.authState.definitionPath)}. Install auth first.`
  );
};

const assertAuthRuntimeReady = (params: {
  cwd: string;
  authState: AuthEnvState;
}) => {
  if (params.authState.runtimeReady) {
    return;
  }

  throw new Error(
    `Auth env sync requires generated auth runtime at ${normalizeRelativePath(params.cwd, params.authState.generatedPath)}. Run \`kitcn codegen\` or \`kitcn dev --bootstrap\` first.`
  );
};

export async function pushEnv(
  options: PushOptions = {},
  deps: PushEnvDeps = {}
) {
  const cwd = process.cwd();
  const authSyncMode = options.authSyncMode ?? 'auto';
  const force = options.force ?? false;
  const rotate = options.rotate ?? false;
  const silent = options.silent ?? false;
  const targetArgs = options.targetArgs ?? [];
  const commandEnv = options.commandEnv;
  const runCommand = deps.runCommand ?? defaultRunCommand;
  const secretGenerator = deps.secretGenerator ?? defaultSecretGenerator;
  const envPath = path.join(cwd, 'convex', '.env');
  const authState = resolveAuthEnvState({
    cwd,
    sharedDir: options.sharedDir,
  });
  const authEnabled = authSyncMode !== 'skip' && authState.installed;
  const source = resolvePushSource({
    allowMissingDefault: authEnabled,
    cwd,
    envPath,
    fromFilePath: options.fromFilePath,
    sourceContent: options.sourceContent,
  });
  const nextVars = { ...source.vars };

  if (!silent) {
    logger.info(
      `🔄 Pushing environment variables to Convex...${force ? ' (FORCE MODE)' : ''}${targetArgs.includes('--prod') ? ' (PRODUCTION)' : ''}\n`
    );
  }

  const pushFilteredEnvEntries = async (vars: Record<string, string>) => {
    const filteredVars = filterPushEnvEntries(vars);
    if (Object.keys(filteredVars).length === 0) {
      return false;
    }

    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kitcn-env-'));
    const tempEnvPath = path.join(tempDir, '.env.push');

    try {
      fs.writeFileSync(tempEnvPath, `${serializeEnvEntries(filteredVars)}\n`);
      await runConvexCommand(
        runCommand,
        cwd,
        buildEnvSetArgs({
          envFilePath: tempEnvPath,
          force,
          targetArgs,
        }),
        commandEnv
      );
      return true;
    } finally {
      fs.rmSync(tempDir, { force: true, recursive: true });
    }
  };

  const ensureManagedAuthSecret = () => {
    const authSecret = ensureAuthSecret({
      envPath,
      preferredSecret: nextVars.BETTER_AUTH_SECRET,
      secretGenerator,
      silent,
    });
    nextVars.BETTER_AUTH_SECRET = authSecret;
  };

  const finalizePush = async () => {
    const pushed = await pushFilteredEnvEntries(nextVars);
    if (!pushed) {
      if (!silent) {
        logger.warn('No environment variables to push.');
      }
      return;
    }
    if (!silent) {
      logger.success('\nEnvironment push complete');
    }
  };

  if (!authEnabled) {
    if (rotate) {
      assertAuthInstalledForRotate({
        cwd,
        authState,
      });
    }
    await finalizePush();
    return;
  }

  if (authSyncMode === 'prepare') {
    ensureManagedAuthSecret();
    await finalizePush();
    return;
  }

  if (authSyncMode === 'complete') {
    assertAuthRuntimeReady({
      cwd,
      authState,
    });
    ensureManagedAuthSecret();
    if (rotate) {
      await runConvexCommand(
        runCommand,
        cwd,
        ['run', AUTH_ROTATE_KEYS_FUNCTION, ...targetArgs],
        commandEnv
      );
      if (!silent) {
        logger.info('Rotated auth keys.');
      }
    }
    const jwksResult = await runConvexCommand(
      runCommand,
      cwd,
      ['run', AUTH_JWKS_FUNCTION, ...targetArgs],
      commandEnv
    );
    nextVars.JWKS = parseConvexRunValue(jwksResult.stdout);
    await finalizePush();
    return;
  }

  assertAuthRuntimeReady({
    cwd,
    authState,
  });
  ensureManagedAuthSecret();

  const pushedInitialEnv = await pushFilteredEnvEntries(nextVars);
  if (!pushedInitialEnv) {
    if (!silent) {
      logger.warn('No environment variables to push.');
    }
    return;
  }

  if (rotate) {
    await runConvexCommand(
      runCommand,
      cwd,
      ['run', AUTH_ROTATE_KEYS_FUNCTION, ...targetArgs],
      commandEnv
    );
    if (!silent) {
      logger.info('Rotated auth keys.');
    }
  }

  const jwksResult = await runConvexCommand(
    runCommand,
    cwd,
    ['run', AUTH_JWKS_FUNCTION, ...targetArgs],
    commandEnv
  );
  nextVars.JWKS = parseConvexRunValue(jwksResult.stdout);
  await finalizePush();
}

export async function pullEnv(
  options: PullOptions = {},
  deps: PullEnvDeps = {}
) {
  const cwd = process.cwd();
  const runCommand = deps.runCommand ?? defaultRunCommand;
  const targetArgs = options.targetArgs ?? [];
  const commandEnv = options.commandEnv;
  const result = await runConvexCommand(
    runCommand,
    cwd,
    ['env', 'list', ...targetArgs],
    commandEnv
  );

  if (options.outFilePath) {
    const outputPath = path.resolve(cwd, options.outFilePath);
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, result.stdout);
    logger.success(`Wrote environment variables to ${options.outFilePath}`);
    return;
  }

  process.stdout.write(result.stdout);
}

export const syncEnv = pushEnv;
