export const FUNCTIONS_DIR_IMPORT_PLACEHOLDER = '__KITCN_FUNCTIONS_DIR__';
export const PLUGIN_CONFIG_IMPORT_PLACEHOLDER =
  '__KITCN_PLUGIN_CONFIG_IMPORT__';
export const PLUGIN_SCHEMA_IMPORT_PLACEHOLDER =
  '__KITCN_PLUGIN_SCHEMA_IMPORT__';
export const PROJECT_CRPC_IMPORT_PLACEHOLDER = '__KITCN_PROJECT_CRPC_IMPORT__';
export const PROJECT_SHARED_API_IMPORT_PLACEHOLDER =
  '__KITCN_PROJECT_SHARED_API_IMPORT__';
export const PROJECT_GET_ENV_IMPORT_PLACEHOLDER =
  '__KITCN_PROJECT_GET_ENV_IMPORT__';
