/**
 * @file Automatically generated by barrelsby.
 */

import { convex as baseConvex } from '@convex-dev/better-auth/plugins';
import type { BetterAuthPlugin } from 'better-auth';

type ConvexPlugin = ReturnType<typeof baseConvex> & BetterAuthPlugin;

export const convex = ((...args: Parameters<typeof baseConvex>) =>
  baseConvex(...args) as ConvexPlugin) as (
  ...args: Parameters<typeof baseConvex>
) => ConvexPlugin;
export * from './adapter';
export * from './adapter-utils';
export * from './create-api';
export type { AuthFunctions, Triggers } from './create-client';
export { createClient } from './create-client';
export * from './define-auth';
export * from './generated-contract';
export type { AuthRuntime } from './generated-contract-disabled';
export * from './helpers';
export * from './types';
