// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

function getGeneratedValue(root: unknown, path: readonly string[]): unknown {
  let current = root;

  for (const segment of path) {
    if (typeof current !== 'object' || current === null) {
      throw new Error(`[better-convex] Invalid generated path: ${path.join('.')}`);
    }
    current = (current as Record<string, unknown>)[segment];
  }

  return current;
}


export const api = {
  messages: {
    create: createApiLeaf<"mutation", typeof import("../functions/messages").create>(getGeneratedValue(convexApi, ["messages","create"]), { type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/messages").list>(getGeneratedValue(convexApi, ["messages","list"]), { type: "query" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
