import fs from 'node:fs';
import path from 'node:path';
import { createJiti } from 'jiti';
import { isValidConvexFile } from '../shared/meta-utils';

/**
 * Generate api.ts with cRPC metadata and client-facing public API refs.
 * Uses runtime imports to extract _crpcMeta from cRPC functions.
 */

type FnMeta = Record<string, unknown>;
type ModuleMeta = Record<string, FnMeta>;
type Meta = Record<string, ModuleMeta>;

/** HTTP route info from _crpcHttpRoute */
type HttpRoute = { path: string; method: string };
type HttpRoutes = Record<string, HttpRoute>;

/** Valid JS identifier pattern for object keys */
const VALID_IDENTIFIER_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/** Pattern to strip .ts extension */
const TS_EXTENSION_RE = /\.ts$/;

type ApiTreeNode = {
  children: Record<string, ApiTreeNode>;
  functions: Array<{
    fnName: string;
    fnType: 'query' | 'mutation' | 'action';
    moduleName: string;
    fnMeta: FnMeta;
  }>;
};

/** CRPC metadata attached to functions at runtime */
type CRPCMeta = {
  type: 'query' | 'mutation' | 'action';
  internal?: boolean;
  auth?: 'optional' | 'required';
  [key: string]: unknown;
};

function listFilesRecursive(cwd: string, relDir = ''): string[] {
  const absDir = path.join(cwd, relDir);
  const entries = fs.readdirSync(absDir, { withFileTypes: true });

  const files: string[] = [];
  for (const entry of entries) {
    const relPath = relDir ? `${relDir}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...listFilesRecursive(cwd, relPath));
      continue;
    }
    if (entry.isFile()) {
      files.push(relPath);
    }
  }
  return files;
}

function ensureRelativeImportPath(value: string): string {
  if (value.startsWith('.') || value.startsWith('/')) {
    return value;
  }
  return `./${value}`;
}

function normalizeImportPath(value: string): string {
  return value.replace(/\\/g, '/');
}

function formatKey(key: string): string {
  return VALID_IDENTIFIER_RE.test(key) ? key : `'${key}'`;
}

function getAccessPath(base: string, segments: string[]): string {
  return segments.reduce(
    (acc, segment) => `${acc}[${JSON.stringify(segment)}]`,
    base
  );
}

function getModuleImportPath(
  outputFile: string,
  functionsDir: string,
  moduleName: string
): string {
  const moduleFile = path.join(functionsDir, moduleName);
  const relativePath = path.relative(path.dirname(outputFile), moduleFile);
  return ensureRelativeImportPath(normalizeImportPath(relativePath));
}

function getRuntimeApiImportPath(
  outputFile: string,
  functionsDir: string
): string {
  const runtimeApiFile = path.join(functionsDir, '_generated', 'api.js');
  const relativePath = path.relative(path.dirname(outputFile), runtimeApiFile);
  return ensureRelativeImportPath(normalizeImportPath(relativePath));
}

function getSchemaImportPath(outputFile: string, functionsDir: string): string {
  const schemaFile = path.join(functionsDir, 'schema');
  const relativePath = path.relative(path.dirname(outputFile), schemaFile);
  return ensureRelativeImportPath(normalizeImportPath(relativePath));
}

function getServerTypesImportPath(
  outputFile: string,
  functionsDir: string
): string {
  const serverTypesFile = path.join(functionsDir, '_generated', 'server');
  const relativePath = path.relative(path.dirname(outputFile), serverTypesFile);
  return ensureRelativeImportPath(normalizeImportPath(relativePath));
}

function getDataModelImportPath(
  outputFile: string,
  functionsDir: string
): string {
  const dataModelFile = path.join(functionsDir, '_generated', 'dataModel');
  const relativePath = path.relative(path.dirname(outputFile), dataModelFile);
  return ensureRelativeImportPath(normalizeImportPath(relativePath));
}

function getHttpImportPath(outputFile: string, functionsDir: string): string {
  const httpFile = path.join(functionsDir, 'http');
  const relativePath = path.relative(path.dirname(outputFile), httpFile);
  return ensureRelativeImportPath(normalizeImportPath(relativePath));
}

function getGeneratedServerOutputFile(functionsDir: string): string {
  return path.join(functionsDir, 'generated.ts');
}

function emitGeneratedServerFile(
  outputFile: string,
  functionsDir: string,
  hasRelationsExport: boolean
): string {
  const serverTypesImportPath = getServerTypesImportPath(
    outputFile,
    functionsDir
  );
  const dataModelImportPath = getDataModelImportPath(outputFile, functionsDir);
  const runtimeApiImportPath = getRuntimeApiImportPath(
    outputFile,
    functionsDir
  );
  const schemaImportPath = getSchemaImportPath(outputFile, functionsDir);
  const moduleNamespace = path.basename(outputFile, '.ts');
  const ormFunctionsAccessor = VALID_IDENTIFIER_RE.test(moduleNamespace)
    ? `.${moduleNamespace}`
    : `[${JSON.stringify(moduleNamespace)}]`;

  if (!hasRelationsExport) {
    return `// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run \`better-convex codegen\` to regenerate.

import { initCRPC as baseInitCRPC } from "better-convex/server";
import type { DataModel } from ${JSON.stringify(dataModelImportPath)};
import type {
  ActionCtx as ServerActionCtx,
  MutationCtx as ServerMutationCtx,
  QueryCtx as ServerQueryCtx,
} from ${JSON.stringify(serverTypesImportPath)};

export type QueryCtx = ServerQueryCtx;
export type MutationCtx = ServerMutationCtx;
export type GenericCtx = QueryCtx | MutationCtx | ServerActionCtx;
export const initCRPC = baseInitCRPC.dataModel<DataModel>();
`;
  }

  return `// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run \`better-convex codegen\` to regenerate.

import { createOrm, type GenericOrmCtx, type OrmFunctions } from "better-convex/orm";
import { initCRPC as baseInitCRPC } from "better-convex/server";
import type { DataModel } from ${JSON.stringify(dataModelImportPath)};
import type {
  ActionCtx as ServerActionCtx,
  MutationCtx as ServerMutationCtx,
  QueryCtx as ServerQueryCtx,
} from ${JSON.stringify(serverTypesImportPath)};
import { internalMutation } from ${JSON.stringify(serverTypesImportPath)};
import { internal } from ${JSON.stringify(runtimeApiImportPath)};
import { relations } from ${JSON.stringify(schemaImportPath)};

const ormFunctions = (internal as unknown as Record<string, OrmFunctions>)${ormFunctionsAccessor};

export const orm = createOrm({
  schema: relations,
  ormFunctions,
  internalMutation,
});

export type OrmCtx<Ctx extends ServerQueryCtx | ServerMutationCtx = ServerQueryCtx> = GenericOrmCtx<Ctx, typeof relations>;
export type QueryCtx = OrmCtx<ServerQueryCtx>;
export type MutationCtx = OrmCtx<ServerMutationCtx>;
export type GenericCtx = QueryCtx | MutationCtx | ServerActionCtx;

export function withOrm<Ctx extends ServerQueryCtx | ServerMutationCtx>(ctx: Ctx) {
  return orm.with(ctx) as OrmCtx<Ctx>;
}

export const initCRPC = baseInitCRPC.dataModel<DataModel>().context({
  query: (ctx) => withOrm(ctx),
  mutation: (ctx) => withOrm(ctx),
});

export const { scheduledMutationBatch, scheduledDelete } = orm.api();
`;
}

function hasNamedExport(filePath: string, exportName: string): boolean {
  if (!fs.existsSync(filePath)) {
    return false;
  }

  const source = fs.readFileSync(filePath, 'utf-8');
  const directPattern = new RegExp(
    `\\bexport\\s+(?:const|let|var|function|class|type|interface)\\s+${exportName}\\b`
  );
  if (directPattern.test(source)) {
    return true;
  }

  const namedExportsPattern = /\bexport\s*{([^}]*)}/g;
  for (const match of source.matchAll(namedExportsPattern)) {
    const exportList = match[1] ?? '';
    const listPattern = new RegExp(`\\b${exportName}\\b`);
    if (listPattern.test(exportList)) {
      return true;
    }
  }

  return false;
}

function createApiTree(meta: Meta): ApiTreeNode {
  const root: ApiTreeNode = { children: {}, functions: [] };

  for (const [moduleName, fns] of Object.entries(meta)) {
    const pathSegments = moduleName.split('/').filter(Boolean);
    let node = root;

    for (const segment of pathSegments) {
      node.children[segment] ??= { children: {}, functions: [] };
      node = node.children[segment]!;
    }

    for (const fnName of Object.keys(fns).sort()) {
      const fnMeta = fns[fnName] ?? {};
      const type = fnMeta.type;
      const fnType =
        type === 'query' || type === 'mutation' || type === 'action'
          ? type
          : 'query';
      node.functions.push({
        fnName,
        fnType,
        moduleName,
        fnMeta: {
          ...fnMeta,
          type: fnType,
        },
      });
    }
  }

  return root;
}

function formatMetaValue(value: unknown): string | null {
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }
  if (typeof value === 'boolean' || typeof value === 'number') {
    return String(value);
  }
  return null;
}

function emitFnMetaLiteral(fnMeta: FnMeta): string {
  const metaProps: string[] = [];
  for (const [key, value] of Object.entries(fnMeta).sort(([a], [b]) =>
    a.localeCompare(b)
  )) {
    if (value === undefined) continue;
    const formatted = formatMetaValue(value);
    if (formatted !== null) {
      metaProps.push(`${key}: ${formatted}`);
    }
  }

  return `{ ${metaProps.join(', ')} }`;
}

function emitHttpRoutes(
  dedupedRoutes: Record<string, HttpRoute>,
  indentLevel: number
): string[] {
  const indent = '  '.repeat(indentLevel);
  const lines: string[] = [];
  for (const [routeKey, route] of Object.entries(dedupedRoutes).sort(
    ([a], [b]) => a.localeCompare(b)
  )) {
    lines.push(
      `${indent}${formatKey(routeKey)}: { path: ${JSON.stringify(route.path)}, method: ${JSON.stringify(route.method)} },`
    );
  }
  return lines;
}

function emitApiObject(
  tree: ApiTreeNode,
  pathSegments: string[],
  outputFile: string,
  functionsDir: string,
  indentLevel: number,
  dedupedRoutes: Record<string, HttpRoute>,
  hasHttpRouterExport: boolean
): string[] {
  const indent = '  '.repeat(indentLevel);
  const lines: string[] = [];

  const childKeys = Object.keys(tree.children).sort((a, b) =>
    a.localeCompare(b)
  );
  const functionEntries = [...tree.functions].sort((a, b) =>
    a.fnName.localeCompare(b.fnName)
  );

  const childSet = new Set(childKeys);
  for (const entry of functionEntries) {
    if (childSet.has(entry.fnName)) {
      throw new Error(
        `Codegen conflict at ${pathSegments.join('/')}: export "${entry.fnName}" conflicts with directory of same name.`
      );
    }
  }

  const mergedKeys = [
    ...childKeys,
    ...functionEntries.map((entry) => entry.fnName),
  ].sort((a, b) => a.localeCompare(b));

  for (const key of mergedKeys) {
    if (childSet.has(key)) {
      const childNode = tree.children[key]!;
      lines.push(`${indent}${formatKey(key)}: {`);
      lines.push(
        ...emitApiObject(
          childNode,
          [...pathSegments, key],
          outputFile,
          functionsDir,
          indentLevel + 1,
          dedupedRoutes,
          hasHttpRouterExport
        )
      );
      lines.push(`${indent}},`);
      continue;
    }

    const fnEntry = functionEntries.find((entry) => entry.fnName === key);
    if (!fnEntry) continue;

    const runtimeAccess = getAccessPath('convexApi', [...pathSegments, key]);
    const moduleImportPath = getModuleImportPath(
      outputFile,
      functionsDir,
      fnEntry.moduleName
    );
    const fnMetaLiteral = emitFnMetaLiteral(fnEntry.fnMeta);

    lines.push(
      `${indent}${formatKey(key)}: createApiLeaf<${JSON.stringify(fnEntry.fnType)}, typeof import(${JSON.stringify(moduleImportPath)}).${key}>(${runtimeAccess}, ${fnMetaLiteral}),`
    );
  }

  if (pathSegments.length === 0) {
    if (hasHttpRouterExport) {
      lines.push(`${indent}http: undefined as unknown as typeof httpRouter,`);
    }
    lines.push(`${indent}_http: {`);
    lines.push(...emitHttpRoutes(dedupedRoutes, indentLevel + 1));
    lines.push(`${indent}},`);
  }

  return lines;
}

export function getConvexConfig(outputDir?: string): {
  functionsDir: string;
  outputFile: string;
} {
  const convexConfigPath = path.join(process.cwd(), 'convex.json');
  const convexConfig = fs.existsSync(convexConfigPath)
    ? JSON.parse(fs.readFileSync(convexConfigPath, 'utf-8'))
    : {};
  // convex.json "functions" is the path to functions dir, default is "convex"
  const functionsDir = convexConfig.functions || 'convex';
  const functionsDirPath = path.join(process.cwd(), functionsDir);

  // Default: convex/shared/api.ts, or custom outputDir/api.ts
  const outputFile = path.join(
    process.cwd(),
    outputDir || 'convex/shared',
    'api.ts'
  );

  return {
    functionsDir: functionsDirPath,
    outputFile,
  };
}

/** HTTP route definition from _crpcHttpRoute */
type CRPCHttpRoute = {
  path: string;
  method: string;
};

/**
 * Check if a value is a CRPCHttpRouter (has _def.router === true)
 */
function isCRPCHttpRouter(value: unknown): value is {
  _def: {
    router: true;
    procedures: Record<string, { _crpcHttpRoute?: CRPCHttpRoute }>;
  };
} {
  return (
    typeof value === 'object' &&
    value !== null &&
    '_def' in value &&
    (value as any)._def?.router === true
  );
}

/**
 * Import a module using jiti and extract cRPC metadata from exports.
 */
async function parseModuleRuntime(
  filePath: string,
  jitiInstance: ReturnType<typeof createJiti>
): Promise<{ meta: ModuleMeta | null; httpRoutes: HttpRoutes }> {
  const result: ModuleMeta = {};
  const httpRoutes: HttpRoutes = {};
  const isHttp = filePath.endsWith('http.ts');

  // Use jiti to import TypeScript files
  const module = await jitiInstance.import(filePath);

  if (!module || typeof module !== 'object') {
    if (isHttp) {
      console.error('  http.ts: module is empty or not an object');
    }
    return { meta: null, httpRoutes: {} };
  }

  // Check each export for _crpcMeta, _crpcHttpRoute, or router
  for (const [name, value] of Object.entries(module)) {
    // Skip private exports
    if (name.startsWith('_')) continue;

    // Check if this is a cRPC function with metadata
    const meta = (value as any)?._crpcMeta as CRPCMeta | undefined;

    if (meta?.type) {
      // Skip internal functions
      if (meta.internal) continue;

      // Extract relevant metadata
      const fnMeta: FnMeta = { type: meta.type };

      if (meta.auth) {
        fnMeta.auth = meta.auth;
      }

      // Copy any additional meta properties (role, rateLimit, dev, etc.)
      for (const [key, val] of Object.entries(meta)) {
        if (key !== 'type' && key !== 'internal' && val !== undefined) {
          fnMeta[key] = val;
        }
      }

      result[name] = fnMeta;
    }

    // Check if this is an HTTP procedure with route metadata
    const httpRoute = (value as any)?._crpcHttpRoute as
      | CRPCHttpRoute
      | undefined;
    if (httpRoute?.path && httpRoute?.method) {
      httpRoutes[name] = {
        path: httpRoute.path,
        method: httpRoute.method,
      };
    }

    // Check if this is a CRPCHttpRouter with _def.procedures
    if (isCRPCHttpRouter(value)) {
      // Extract routes from router's flat procedures map
      for (const [procPath, procedure] of Object.entries(
        value._def.procedures
      )) {
        const route = procedure._crpcHttpRoute;
        if (route?.path && route?.method) {
          httpRoutes[procPath] = {
            path: route.path,
            method: route.method,
          };
        }
      }
    }
  }

  return {
    meta: Object.keys(result).length > 0 ? result : null,
    httpRoutes,
  };
}

export async function generateMeta(
  outputDir?: string,
  options?: { debug?: boolean; silent?: boolean }
): Promise<void> {
  const startTime = Date.now();
  const { functionsDir, outputFile } = getConvexConfig(outputDir);
  const debug = options?.debug ?? false;
  const silent = options?.silent ?? false;

  if (debug) {
    console.info('🔍 Scanning Convex functions for cRPC metadata...\n');
  }

  // Create jiti instance for importing TypeScript files
  const jitiInstance = createJiti(process.cwd(), {
    interopDefault: true,
    moduleCache: false,
  });

  const meta: Meta = {};
  const allHttpRoutes: HttpRoutes = {};
  let totalFunctions = 0;

  const files = listFilesRecursive(functionsDir).filter(
    (file) => file.endsWith('.ts') && isValidConvexFile(file)
  );

  for (const file of files) {
    const filePath = path.join(functionsDir, file);
    // Use path (minus .ts) as namespace key: 'items/queries' for nested files
    const moduleName = file.replace(TS_EXTENSION_RE, '');

    try {
      const { meta: moduleMeta, httpRoutes } = await parseModuleRuntime(
        filePath,
        jitiInstance
      );

      if (moduleMeta) {
        meta[moduleName] = moduleMeta;
        const fnCount = Object.keys(moduleMeta).length;
        totalFunctions += fnCount;
        if (debug) {
          console.info(`  ✓ ${moduleName}: ${fnCount} functions`);
        }
      }

      // Merge HTTP routes
      if (Object.keys(httpRoutes).length > 0 && debug) {
        console.info(
          `  ✓ ${moduleName}: ${Object.keys(httpRoutes).length} HTTP routes`
        );
      }
      Object.assign(allHttpRoutes, httpRoutes);
    } catch (error) {
      // Always log http.ts errors as they contain critical HTTP routes
      if (debug || file === 'http.ts') {
        console.error(`  ⚠ Failed to parse ${file}:`, error);
      }
    }
  }

  // Dedupe HTTP routes: prefer nested paths (todos.get) over flat (get)
  // by keeping only routes where no other route has same path with longer key
  const routesByPath = new Map<string, { key: string; route: HttpRoute }[]>();
  for (const [key, route] of Object.entries(allHttpRoutes)) {
    const pathKey = `${route.path}:${route.method}`;
    const existing = routesByPath.get(pathKey) || [];
    existing.push({ key, route });
    routesByPath.set(pathKey, existing);
  }

  // Keep only the longest key for each path (nested paths are longer)
  const dedupedRoutes: Record<string, HttpRoute> = {};
  for (const entries of routesByPath.values()) {
    const best = entries.reduce((a, b) =>
      a.key.length >= b.key.length ? a : b
    );
    dedupedRoutes[best.key] = best.route;
  }

  const runtimeApiImportPath = getRuntimeApiImportPath(
    outputFile,
    functionsDir
  );
  const schemaImportPath = getSchemaImportPath(outputFile, functionsDir);
  const httpImportPath = getHttpImportPath(outputFile, functionsDir);
  const hasTablesExport = hasNamedExport(
    path.join(functionsDir, 'schema.ts'),
    'tables'
  );
  const hasRelationsExport = hasNamedExport(
    path.join(functionsDir, 'schema.ts'),
    'relations'
  );
  const hasHttpRouterExport = hasNamedExport(
    path.join(functionsDir, 'http.ts'),
    'httpRouter'
  );

  const apiTree = createApiTree(meta);
  const hasRootHttpNamespace =
    Object.hasOwn(apiTree.children, 'http') ||
    apiTree.functions.some((entry) => entry.fnName === 'http');
  if (hasRootHttpNamespace) {
    throw new Error(
      'Codegen conflict: root "http" namespace is reserved for generated HTTP router types. Rename your Convex module/function.'
    );
  }
  const apiObjectLines = emitApiObject(
    apiTree,
    [],
    outputFile,
    functionsDir,
    1,
    dedupedRoutes,
    hasHttpRouterExport
  );
  const apiObjectBody =
    apiObjectLines.length > 0 ? `\n${apiObjectLines.join('\n')}\n` : '\n';

  const serverTypeImports =
    'import type { inferApiInputs, inferApiOutputs } from "better-convex/server";';

  const ormTypeImports = [
    hasTablesExport ? 'InferInsertModel' : null,
    hasTablesExport ? 'InferSelectModel' : null,
  ].filter((item): item is string => !!item);

  const optionalImports = [
    ormTypeImports.length > 0
      ? `import type { ${ormTypeImports.join(', ')} } from "better-convex/orm";`
      : null,
    hasHttpRouterExport
      ? `import type { httpRouter } from ${JSON.stringify(httpImportPath)};`
      : null,
    hasTablesExport
      ? `import type { tables } from ${JSON.stringify(schemaImportPath)};`
      : null,
  ]
    .filter((line): line is string => !!line)
    .join('\n');

  const apiTypeLine = 'export type Api = typeof api;';

  const optionalTypeExports = [
    hasTablesExport
      ? `
export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;`
      : null,
  ]
    .filter((entry): entry is string => !!entry)
    .join('\n');

  const output = `// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run \`better-convex codegen\` to regenerate.

import { createApiLeaf } from "better-convex/server";
${serverTypeImports}
import { api as convexApi } from ${JSON.stringify(runtimeApiImportPath)};
${optionalImports ? `\n${optionalImports}` : ''}

export const api = {${apiObjectBody}} as const;

${apiTypeLine}
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;
${optionalTypeExports}
`;

  const serverOutputFile = getGeneratedServerOutputFile(functionsDir);
  const serverOutput = emitGeneratedServerFile(
    serverOutputFile,
    functionsDir,
    hasRelationsExport
  );

  // Ensure output directory exists
  const outputDirname = path.dirname(outputFile);

  if (!fs.existsSync(outputDirname)) {
    fs.mkdirSync(outputDirname, { recursive: true });
  }

  fs.writeFileSync(outputFile, output);
  fs.writeFileSync(serverOutputFile, serverOutput);

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);
  const time = new Date().toLocaleTimeString('en-US', {
    hour12: false,
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  if (!silent) {
    if (debug) {
      console.info(`\n✅ Generated ${outputFile}`);
      console.info(`✅ Generated ${serverOutputFile}`);
      console.info(
        `   ${Object.keys(meta).length} modules, ${totalFunctions} functions`
      );
    } else {
      console.info(`✔ ${time} Convex api ready! (${elapsed}s)`);
    }
  }
}
