import * as childProcess from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'dotenv';
import { logger } from './utils/logger.js';

export interface SyncOptions {
  auth?: boolean;
  force?: boolean;
  prod?: boolean;
}

export async function syncEnv(options: SyncOptions = {}) {
  const { auth = false, force = false, prod = false } = options;
  const prodFlag = prod ? ' --prod' : '';

  logger.info(
    `🔄 Syncing environment variables from convex/.env to Convex...${force ? ' (FORCE MODE)' : ''}${prod ? ' (PRODUCTION)' : ''}\n`
  );

  // Read convex/.env
  const envPath = path.join(process.cwd(), 'convex', '.env');

  if (!fs.existsSync(envPath)) {
    logger.error('convex/.env file not found');
    process.exit(1);
  }

  const envContent = fs.readFileSync(envPath, 'utf-8');
  const envVars = parse(envContent);

  // Auth-specific: Generate BETTER_AUTH_SECRET and JWKS
  if (auth) {
    // Generate BETTER_AUTH_SECRET if not present
    if (!envVars.BETTER_AUTH_SECRET) {
      try {
        const secret = childProcess
          .execSync('openssl rand -base64 32', {
            encoding: 'utf-8',
          })
          .trim();
        envVars.BETTER_AUTH_SECRET = secret;
        logger.info('Generated BETTER_AUTH_SECRET');

        fs.appendFileSync(
          envPath,
          `\n# Generated by better-convex env sync --auth\nBETTER_AUTH_SECRET=${secret}\n`
        );
      } catch {
        logger.warn(
          'Could not generate BETTER_AUTH_SECRET (openssl not available)'
        );
      }
    }

    // Generate JWKS if not set
    try {
      const existingJwks = childProcess
        .execSync(`npx convex env get JWKS${prodFlag}`, {
          encoding: 'utf-8',
          stdio: ['pipe', 'pipe', 'ignore'],
        })
        .trim();

      if (
        !existingJwks ||
        existingJwks === 'undefined' ||
        existingJwks.includes('not set')
      ) {
        logger.info('Generating JWKS...');
        childProcess.execSync(
          `npx convex run auth:getLatestJwks${prodFlag} | npx convex env set JWKS${prodFlag}`,
          { stdio: 'inherit' }
        );
        logger.success('JWKS initialized');
      } else {
        logger.success('JWKS already set');
      }
    } catch {
      logger.warn(
        'Could not generate JWKS (auth:getLatestJwks not available yet)'
      );
    }
  }

  // Log deployment info
  try {
    const deployment = childProcess
      .execSync(`npx convex env get CONVEX_DEPLOYMENT${prodFlag}`, {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'ignore'],
      })
      .trim();
    logger.info(`📍 Current Convex deployment: ${deployment || 'anonymous'}\n`);
  } catch {
    logger.info('Using anonymous Convex deployment\n');
  }

  // Sync each variable
  let errorCount = 0;

  for (const [varName, value] of Object.entries(envVars)) {
    if (!value) {
      logger.info(`${varName}: Empty value, skipping`);
      continue;
    }

    try {
      if (!force) {
        const currentValue = childProcess
          .execSync(`npx convex env get ${varName}${prodFlag}`, {
            encoding: 'utf-8',
            stdio: ['pipe', 'pipe', 'ignore'],
          })
          .trim();

        if (currentValue === value) {
          logger.success(`${varName}: Already up to date`);
          continue;
        }
      }

      childProcess.execSync(
        `npx convex env set ${varName}="${value}"${prodFlag}`,
        {
          stdio: ['pipe', 'pipe', 'pipe'],
        }
      );
      logger.success(`${varName}: Updated`);
    } catch {
      try {
        childProcess.execSync(
          `npx convex env set ${varName}="${value}"${prodFlag}`,
          {
            stdio: ['pipe', 'pipe', 'pipe'],
          }
        );
        logger.success(`${varName}: Set successfully`);
      } catch {
        logger.error(`${varName}: Failed to set`);
        errorCount++;
      }
    }
  }

  if (errorCount > 0) {
    logger.warn(
      '\nSome variables failed to sync. Please check your Convex deployment.'
    );
    process.exit(1);
  }

  logger.success('\nEnvironment sync complete');
}
