// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";

import type { InferInsertModel, InferSelectModel } from "kitcn/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  admin: {
    checkUserAdminStatus: createApiLeaf<"query", typeof import("../functions/admin").checkUserAdminStatus>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/admin").checkUserAdminStatus>("admin:checkUserAdminStatus"), { auth: "required", role: "admin", type: "query" }),
    getAllUsers: createApiLeaf<"query", typeof import("../functions/admin").getAllUsers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/admin").getAllUsers>("admin:getAllUsers"), { auth: "required", limit: 20, type: "query" }),
    getDashboardStats: createApiLeaf<"query", typeof import("../functions/admin").getDashboardStats>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/admin").getDashboardStats>("admin:getDashboardStats"), { auth: "required", role: "admin", type: "query" }),
    grantAdminByEmail: createApiLeaf<"mutation", typeof import("../functions/admin").grantAdminByEmail>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/admin").grantAdminByEmail>("admin:grantAdminByEmail"), { auth: "required", role: "admin", type: "mutation" }),
    updateUserRole: createApiLeaf<"mutation", typeof import("../functions/admin").updateUserRole>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/admin").updateUserRole>("admin:updateUserRole"), { auth: "required", role: "admin", type: "mutation" }),
  },
  aggregateDemo: {
    exerciseIdempotentTrigger: createApiLeaf<"mutation", typeof import("../functions/aggregateDemo").exerciseIdempotentTrigger>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/aggregateDemo").exerciseIdempotentTrigger>("aggregateDemo:exerciseIdempotentTrigger"), { auth: "required", type: "mutation" }),
    getSnapshot: createApiLeaf<"query", typeof import("../functions/aggregateDemo").getSnapshot>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/aggregateDemo").getSnapshot>("aggregateDemo:getSnapshot"), { auth: "required", type: "query" }),
    runDirectOp: createApiLeaf<"mutation", typeof import("../functions/aggregateDemo").runDirectOp>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/aggregateDemo").runDirectOp>("aggregateDemo:runDirectOp"), { auth: "required", type: "mutation" }),
    toggleRandomFillReset: createApiLeaf<"mutation", typeof import("../functions/aggregateDemo").toggleRandomFillReset>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/aggregateDemo").toggleRandomFillReset>("aggregateDemo:toggleRandomFillReset"), { auth: "required", type: "mutation" }),
  },
  authDemo: {
    getAuthState: createApiLeaf<"query", typeof import("../functions/authDemo").getAuthState>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/authDemo").getAuthState>("authDemo:getAuthState"), { auth: "required", type: "query" }),
    getSnapshot: createApiLeaf<"query", typeof import("../functions/authDemo").getSnapshot>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/authDemo").getSnapshot>("authDemo:getSnapshot"), { auth: "required", type: "query" }),
    runCoverage: createApiLeaf<"action", typeof import("../functions/authDemo").runCoverage>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/authDemo").runCoverage>("authDemo:runCoverage"), { auth: "required", type: "action" }),
    runScenario: createApiLeaf<"action", typeof import("../functions/authDemo").runScenario>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/authDemo").runScenario>("authDemo:runScenario"), { auth: "required", type: "action" }),
  },
  items: {
    queries: {
      get: createApiLeaf<"query", typeof import("../functions/items/queries").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/items/queries").get>("items/queries:get"), { type: "query" }),
      list: createApiLeaf<"query", typeof import("../functions/items/queries").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/items/queries").list>("items/queries:list"), { type: "query" }),
    },
  },
  migrationDemo: {
    cancel: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").cancel>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/migrationDemo").cancel>("migrationDemo:cancel"), { auth: "required", type: "mutation" }),
    getStatus: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").getStatus>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/migrationDemo").getStatus>("migrationDemo:getStatus"), { auth: "required", type: "mutation" }),
    runDown: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").runDown>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/migrationDemo").runDown>("migrationDemo:runDown"), { auth: "required", type: "mutation" }),
    runUp: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").runUp>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/migrationDemo").runUp>("migrationDemo:runUp"), { auth: "required", type: "mutation" }),
  },
  organization: {
    acceptInvitation: createApiLeaf<"mutation", typeof import("../functions/organization").acceptInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").acceptInvitation>("organization:acceptInvitation"), { auth: "required", type: "mutation" }),
    addMember: createApiLeaf<"mutation", typeof import("../functions/organization").addMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").addMember>("organization:addMember"), { auth: "required", type: "mutation" }),
    cancelInvitation: createApiLeaf<"mutation", typeof import("../functions/organization").cancelInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").cancelInvitation>("organization:cancelInvitation"), { auth: "required", type: "mutation" }),
    checkSlug: createApiLeaf<"query", typeof import("../functions/organization").checkSlug>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").checkSlug>("organization:checkSlug"), { auth: "required", type: "query" }),
    createOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").createOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").createOrganization>("organization:createOrganization"), { auth: "required", type: "mutation" }),
    deleteOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").deleteOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").deleteOrganization>("organization:deleteOrganization"), { auth: "required", type: "mutation" }),
    getActiveMember: createApiLeaf<"query", typeof import("../functions/organization").getActiveMember>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").getActiveMember>("organization:getActiveMember"), { auth: "required", type: "query" }),
    getOrganization: createApiLeaf<"query", typeof import("../functions/organization").getOrganization>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").getOrganization>("organization:getOrganization"), { auth: "required", type: "query" }),
    getOrganizationOverview: createApiLeaf<"query", typeof import("../functions/organization").getOrganizationOverview>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").getOrganizationOverview>("organization:getOrganizationOverview"), { auth: "required", type: "query" }),
    inviteMember: createApiLeaf<"mutation", typeof import("../functions/organization").inviteMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").inviteMember>("organization:inviteMember"), { auth: "required", type: "mutation" }),
    leaveOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").leaveOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").leaveOrganization>("organization:leaveOrganization"), { auth: "required", type: "mutation" }),
    listMembers: createApiLeaf<"query", typeof import("../functions/organization").listMembers>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").listMembers>("organization:listMembers"), { auth: "required", type: "query" }),
    listOrganizations: createApiLeaf<"query", typeof import("../functions/organization").listOrganizations>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").listOrganizations>("organization:listOrganizations"), { auth: "required", type: "query" }),
    listPendingInvitations: createApiLeaf<"query", typeof import("../functions/organization").listPendingInvitations>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").listPendingInvitations>("organization:listPendingInvitations"), { auth: "required", type: "query" }),
    listUserInvitations: createApiLeaf<"query", typeof import("../functions/organization").listUserInvitations>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").listUserInvitations>("organization:listUserInvitations"), { auth: "required", type: "query" }),
    listUserOrganizations: createApiLeaf<"query", typeof import("../functions/organization").listUserOrganizations>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/organization").listUserOrganizations>("organization:listUserOrganizations"), { auth: "required", type: "query" }),
    rejectInvitation: createApiLeaf<"mutation", typeof import("../functions/organization").rejectInvitation>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").rejectInvitation>("organization:rejectInvitation"), { auth: "required", type: "mutation" }),
    removeMember: createApiLeaf<"mutation", typeof import("../functions/organization").removeMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").removeMember>("organization:removeMember"), { auth: "required", type: "mutation" }),
    setActiveOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").setActiveOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").setActiveOrganization>("organization:setActiveOrganization"), { auth: "required", type: "mutation" }),
    updateMemberRole: createApiLeaf<"mutation", typeof import("../functions/organization").updateMemberRole>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").updateMemberRole>("organization:updateMemberRole"), { auth: "required", type: "mutation" }),
    updateOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").updateOrganization>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/organization").updateOrganization>("organization:updateOrganization"), { auth: "required", type: "mutation" }),
  },
  ormDemo: {
    clearPolymorphic: createApiLeaf<"mutation", typeof import("../functions/ormDemo").clearPolymorphic>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/ormDemo").clearPolymorphic>("ormDemo:clearPolymorphic"), { auth: "required", type: "mutation" }),
    getSnapshot: createApiLeaf<"query", typeof import("../functions/ormDemo").getSnapshot>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/ormDemo").getSnapshot>("ormDemo:getSnapshot"), { auth: "required", type: "query" }),
    runCoverage: createApiLeaf<"mutation", typeof import("../functions/ormDemo").runCoverage>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/ormDemo").runCoverage>("ormDemo:runCoverage"), { auth: "required", type: "mutation" }),
    seedPolymorphic: createApiLeaf<"mutation", typeof import("../functions/ormDemo").seedPolymorphic>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/ormDemo").seedPolymorphic>("ormDemo:seedPolymorphic"), { auth: "required", type: "mutation" }),
  },
  projects: {
    addMember: createApiLeaf<"mutation", typeof import("../functions/projects").addMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").addMember>("projects:addMember"), { auth: "required", type: "mutation" }),
    archive: createApiLeaf<"mutation", typeof import("../functions/projects").archive>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").archive>("projects:archive"), { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/projects").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").create>("projects:create"), { auth: "required", type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/projects").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/projects").get>("projects:get"), { auth: "optional", type: "query" }),
    leave: createApiLeaf<"mutation", typeof import("../functions/projects").leave>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").leave>("projects:leave"), { auth: "required", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/projects").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/projects").list>("projects:list"), { auth: "optional", limit: 20, type: "query" }),
    listForDropdown: createApiLeaf<"query", typeof import("../functions/projects").listForDropdown>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/projects").listForDropdown>("projects:listForDropdown"), { auth: "required", type: "query" }),
    removeMember: createApiLeaf<"mutation", typeof import("../functions/projects").removeMember>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").removeMember>("projects:removeMember"), { auth: "required", type: "mutation" }),
    restore: createApiLeaf<"mutation", typeof import("../functions/projects").restore>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").restore>("projects:restore"), { auth: "required", type: "mutation" }),
    transfer: createApiLeaf<"mutation", typeof import("../functions/projects").transfer>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").transfer>("projects:transfer"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/projects").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/projects").update>("projects:update"), { auth: "required", type: "mutation" }),
  },
  public: {
    hello: createApiLeaf<"query", typeof import("../functions/public").hello>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/public").hello>("public:hello"), { type: "query" }),
  },
  ratelimitDemo: {
    consumeInteractive: createApiLeaf<"mutation", typeof import("../functions/ratelimitDemo").consumeInteractive>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/ratelimitDemo").consumeInteractive>("ratelimitDemo:consumeInteractive"), { ratelimit: "interactive", type: "mutation" }),
    getInteractiveStatus: createApiLeaf<"query", typeof import("../functions/ratelimitDemo").getInteractiveStatus>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/ratelimitDemo").getInteractiveStatus>("ratelimitDemo:getInteractiveStatus"), { type: "query" }),
    getSnapshot: createApiLeaf<"query", typeof import("../functions/ratelimitDemo").getSnapshot>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/ratelimitDemo").getSnapshot>("ratelimitDemo:getSnapshot"), { auth: "required", type: "query" }),
    resetInteractive: createApiLeaf<"mutation", typeof import("../functions/ratelimitDemo").resetInteractive>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/ratelimitDemo").resetInteractive>("ratelimitDemo:resetInteractive"), { ratelimit: "interactive", type: "mutation" }),
    runCoverage: createApiLeaf<"action", typeof import("../functions/ratelimitDemo").runCoverage>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/ratelimitDemo").runCoverage>("ratelimitDemo:runCoverage"), { auth: "required", type: "action" }),
  },
  seed: {
    generateSamples: createApiLeaf<"action", typeof import("../functions/seed").generateSamples>(createGeneratedFunctionReference<"action", "public", typeof import("../functions/seed").generateSamples>("seed:generateSamples"), { auth: "required", type: "action" }),
  },
  tags: {
    create: createApiLeaf<"mutation", typeof import("../functions/tags").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tags").create>("tags:create"), { auth: "required", type: "mutation" }),
    deleteTag: createApiLeaf<"mutation", typeof import("../functions/tags").deleteTag>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tags").deleteTag>("tags:deleteTag"), { auth: "required", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/tags").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tags").list>("tags:list"), { auth: "required", type: "query" }),
    merge: createApiLeaf<"mutation", typeof import("../functions/tags").merge>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tags").merge>("tags:merge"), { auth: "required", type: "mutation" }),
    popular: createApiLeaf<"query", typeof import("../functions/tags").popular>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/tags").popular>("tags:popular"), { auth: "required", type: "query" }),
    update: createApiLeaf<"mutation", typeof import("../functions/tags").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/tags").update>("tags:update"), { auth: "required", type: "mutation" }),
  },
  todoComments: {
    addComment: createApiLeaf<"mutation", typeof import("../functions/todoComments").addComment>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todoComments").addComment>("todoComments:addComment"), { auth: "required", type: "mutation" }),
    deleteComment: createApiLeaf<"mutation", typeof import("../functions/todoComments").deleteComment>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todoComments").deleteComment>("todoComments:deleteComment"), { auth: "required", type: "mutation" }),
    getCommentThread: createApiLeaf<"query", typeof import("../functions/todoComments").getCommentThread>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/todoComments").getCommentThread>("todoComments:getCommentThread"), { type: "query" }),
    getTodoComments: createApiLeaf<"query", typeof import("../functions/todoComments").getTodoComments>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/todoComments").getTodoComments>("todoComments:getTodoComments"), { auth: "optional", limit: 20, type: "query" }),
    getUserComments: createApiLeaf<"query", typeof import("../functions/todoComments").getUserComments>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/todoComments").getUserComments>("todoComments:getUserComments"), { auth: "optional", limit: 20, type: "query" }),
    updateComment: createApiLeaf<"mutation", typeof import("../functions/todoComments").updateComment>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todoComments").updateComment>("todoComments:updateComment"), { auth: "required", type: "mutation" }),
  },
  todos: {
    bulkDelete: createApiLeaf<"mutation", typeof import("../functions/todos").bulkDelete>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todos").bulkDelete>("todos:bulkDelete"), { auth: "required", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/todos").create>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todos").create>("todos:create"), { auth: "required", type: "mutation" }),
    deleteTodo: createApiLeaf<"mutation", typeof import("../functions/todos").deleteTodo>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todos").deleteTodo>("todos:deleteTodo"), { auth: "required", type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/todos").get>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/todos").get>("todos:get"), { auth: "required", type: "query" }),
    list: createApiLeaf<"query", typeof import("../functions/todos").list>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/todos").list>("todos:list"), { auth: "optional", limit: 20, type: "query" }),
    restore: createApiLeaf<"mutation", typeof import("../functions/todos").restore>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todos").restore>("todos:restore"), { auth: "required", type: "mutation" }),
    search: createApiLeaf<"query", typeof import("../functions/todos").search>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/todos").search>("todos:search"), { auth: "optional", limit: 20, type: "query" }),
    toggleComplete: createApiLeaf<"mutation", typeof import("../functions/todos").toggleComplete>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todos").toggleComplete>("todos:toggleComplete"), { auth: "required", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/todos").update>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/todos").update>("todos:update"), { auth: "required", type: "mutation" }),
  },
  triggerDemo: {
    getSnapshot: createApiLeaf<"query", typeof import("../functions/triggerDemo").getSnapshot>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/triggerDemo").getSnapshot>("triggerDemo:getSnapshot"), { auth: "required", type: "query" }),
    runCoverage: createApiLeaf<"mutation", typeof import("../functions/triggerDemo").runCoverage>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/triggerDemo").runCoverage>("triggerDemo:runCoverage"), { auth: "required", type: "mutation" }),
  },
  user: {
    getCurrentUser: createApiLeaf<"query", typeof import("../functions/user").getCurrentUser>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/user").getCurrentUser>("user:getCurrentUser"), { auth: "required", type: "query" }),
    getIsAuthenticated: createApiLeaf<"query", typeof import("../functions/user").getIsAuthenticated>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/user").getIsAuthenticated>("user:getIsAuthenticated"), { type: "query" }),
    getSessionUser: createApiLeaf<"query", typeof import("../functions/user").getSessionUser>(createGeneratedFunctionReference<"query", "public", typeof import("../functions/user").getSessionUser>("user:getSessionUser"), { auth: "optional", type: "query" }),
    updateSettings: createApiLeaf<"mutation", typeof import("../functions/user").updateSettings>(createGeneratedFunctionReference<"mutation", "public", typeof import("../functions/user").updateSettings>("user:updateSettings"), { auth: "required", type: "mutation" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
    'examples.allCombinedExample': { path: "/api/examples/items/:id/tags", method: "POST" },
    'examples.inputExample': { path: "/api/examples/items", method: "POST" },
    'examples.paramsExample': { path: "/api/examples/items/:id", method: "GET" },
    'examples.paramsInputExample': { path: "/api/examples/items/:id", method: "PATCH" },
    'examples.paramsSearchParamsExample': { path: "/api/examples/items/:id/history", method: "GET" },
    'examples.redirectExample': { path: "/api/old-path", method: "GET" },
    'examples.searchExample': { path: "/api/examples/search", method: "GET" },
    'examples.uploadExample': { path: "/api/examples/upload", method: "POST" },
    'examples.webhook': { path: "/webhooks/example", method: "POST" },
    health: { path: "/api/health", method: "GET" },
    resendWebhook: { path: "/resend-webhook", method: "POST" },
    'todos.create': { path: "/api/todos", method: "POST" },
    'todos.delete': { path: "/api/todos/:id", method: "DELETE" },
    'todos.download': { path: "/api/todos/export/:format", method: "GET" },
    'todos.get': { path: "/api/todos/:id", method: "GET" },
    'todos.list': { path: "/api/todos", method: "GET" },
    'todos.update': { path: "/api/todos/:id", method: "PATCH" },
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
