// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";

import type { InferInsertModel, InferSelectModel } from "better-convex/orm";
import type { httpRouter } from "../functions/http";
import type { tables } from "../functions/schema";

export const api = {
  admin: {
    checkUserAdminStatus: createApiLeaf<"query", typeof import("../functions/admin").checkUserAdminStatus>(convexApi["admin"]["checkUserAdminStatus"], { auth: "required", role: "admin", type: "query" }),
    getAllUsers: createApiLeaf<"query", typeof import("../functions/admin").getAllUsers>(convexApi["admin"]["getAllUsers"], { auth: "required", limit: 20, type: "query" }),
    getDashboardStats: createApiLeaf<"query", typeof import("../functions/admin").getDashboardStats>(convexApi["admin"]["getDashboardStats"], { auth: "required", role: "admin", type: "query" }),
    grantAdminByEmail: createApiLeaf<"mutation", typeof import("../functions/admin").grantAdminByEmail>(convexApi["admin"]["grantAdminByEmail"], { auth: "required", role: "admin", type: "mutation" }),
    updateUserRole: createApiLeaf<"mutation", typeof import("../functions/admin").updateUserRole>(convexApi["admin"]["updateUserRole"], { auth: "required", role: "admin", type: "mutation" }),
  },
  aggregateDemo: {
    exerciseIdempotentTrigger: createApiLeaf<"mutation", typeof import("../functions/aggregateDemo").exerciseIdempotentTrigger>(convexApi["aggregateDemo"]["exerciseIdempotentTrigger"], { auth: "required", type: "mutation" }),
    getSnapshot: createApiLeaf<"query", typeof import("../functions/aggregateDemo").getSnapshot>(convexApi["aggregateDemo"]["getSnapshot"], { auth: "required", type: "query" }),
    runDirectOp: createApiLeaf<"mutation", typeof import("../functions/aggregateDemo").runDirectOp>(convexApi["aggregateDemo"]["runDirectOp"], { auth: "required", type: "mutation" }),
    toggleRandomFillReset: createApiLeaf<"mutation", typeof import("../functions/aggregateDemo").toggleRandomFillReset>(convexApi["aggregateDemo"]["toggleRandomFillReset"], { auth: "required", type: "mutation" }),
  },
  items: {
    queries: {
      get: createApiLeaf<"query", typeof import("../functions/items/queries").get>(convexApi["items"]["queries"]["get"], { type: "query" }),
      list: createApiLeaf<"query", typeof import("../functions/items/queries").list>(convexApi["items"]["queries"]["list"], { type: "query" }),
    },
  },
  migrationDemo: {
    cancel: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").cancel>(convexApi["migrationDemo"]["cancel"], { auth: "required", type: "mutation" }),
    getStatus: createApiLeaf<"query", typeof import("../functions/migrationDemo").getStatus>(convexApi["migrationDemo"]["getStatus"], { auth: "required", type: "query" }),
    runDown: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").runDown>(convexApi["migrationDemo"]["runDown"], { auth: "required", type: "mutation" }),
    runUp: createApiLeaf<"mutation", typeof import("../functions/migrationDemo").runUp>(convexApi["migrationDemo"]["runUp"], { auth: "required", type: "mutation" }),
  },
  organization: {
    acceptInvitation: createApiLeaf<"mutation", typeof import("../functions/organization").acceptInvitation>(convexApi["organization"]["acceptInvitation"], { auth: "required", type: "mutation" }),
    addMember: createApiLeaf<"mutation", typeof import("../functions/organization").addMember>(convexApi["organization"]["addMember"], { auth: "required", rateLimit: "organization/addMember", type: "mutation" }),
    cancelInvitation: createApiLeaf<"mutation", typeof import("../functions/organization").cancelInvitation>(convexApi["organization"]["cancelInvitation"], { auth: "required", rateLimit: "organization/cancelInvite", type: "mutation" }),
    checkSlug: createApiLeaf<"query", typeof import("../functions/organization").checkSlug>(convexApi["organization"]["checkSlug"], { auth: "required", type: "query" }),
    createOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").createOrganization>(convexApi["organization"]["createOrganization"], { auth: "required", rateLimit: "organization/create", type: "mutation" }),
    deleteOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").deleteOrganization>(convexApi["organization"]["deleteOrganization"], { auth: "required", type: "mutation" }),
    getActiveMember: createApiLeaf<"query", typeof import("../functions/organization").getActiveMember>(convexApi["organization"]["getActiveMember"], { auth: "required", type: "query" }),
    getOrganization: createApiLeaf<"query", typeof import("../functions/organization").getOrganization>(convexApi["organization"]["getOrganization"], { auth: "required", type: "query" }),
    getOrganizationOverview: createApiLeaf<"query", typeof import("../functions/organization").getOrganizationOverview>(convexApi["organization"]["getOrganizationOverview"], { auth: "required", type: "query" }),
    inviteMember: createApiLeaf<"mutation", typeof import("../functions/organization").inviteMember>(convexApi["organization"]["inviteMember"], { auth: "required", rateLimit: "organization/invite", type: "mutation" }),
    leaveOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").leaveOrganization>(convexApi["organization"]["leaveOrganization"], { auth: "required", rateLimit: "organization/leave", type: "mutation" }),
    listMembers: createApiLeaf<"query", typeof import("../functions/organization").listMembers>(convexApi["organization"]["listMembers"], { auth: "required", type: "query" }),
    listOrganizations: createApiLeaf<"query", typeof import("../functions/organization").listOrganizations>(convexApi["organization"]["listOrganizations"], { auth: "required", type: "query" }),
    listPendingInvitations: createApiLeaf<"query", typeof import("../functions/organization").listPendingInvitations>(convexApi["organization"]["listPendingInvitations"], { auth: "required", type: "query" }),
    listUserInvitations: createApiLeaf<"query", typeof import("../functions/organization").listUserInvitations>(convexApi["organization"]["listUserInvitations"], { auth: "required", type: "query" }),
    listUserOrganizations: createApiLeaf<"query", typeof import("../functions/organization").listUserOrganizations>(convexApi["organization"]["listUserOrganizations"], { auth: "required", type: "query" }),
    rejectInvitation: createApiLeaf<"mutation", typeof import("../functions/organization").rejectInvitation>(convexApi["organization"]["rejectInvitation"], { auth: "required", rateLimit: "organization/rejectInvite", type: "mutation" }),
    removeMember: createApiLeaf<"mutation", typeof import("../functions/organization").removeMember>(convexApi["organization"]["removeMember"], { auth: "required", rateLimit: "organization/removeMember", type: "mutation" }),
    setActiveOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").setActiveOrganization>(convexApi["organization"]["setActiveOrganization"], { auth: "required", rateLimit: "organization/setActive", type: "mutation" }),
    updateMemberRole: createApiLeaf<"mutation", typeof import("../functions/organization").updateMemberRole>(convexApi["organization"]["updateMemberRole"], { auth: "required", rateLimit: "organization/updateRole", type: "mutation" }),
    updateOrganization: createApiLeaf<"mutation", typeof import("../functions/organization").updateOrganization>(convexApi["organization"]["updateOrganization"], { auth: "required", rateLimit: "organization/update", type: "mutation" }),
  },
  projects: {
    addMember: createApiLeaf<"mutation", typeof import("../functions/projects").addMember>(convexApi["projects"]["addMember"], { auth: "required", rateLimit: "project/member", type: "mutation" }),
    archive: createApiLeaf<"mutation", typeof import("../functions/projects").archive>(convexApi["projects"]["archive"], { auth: "required", rateLimit: "project/update", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/projects").create>(convexApi["projects"]["create"], { auth: "required", rateLimit: "project/create", type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/projects").get>(convexApi["projects"]["get"], { auth: "optional", type: "query" }),
    leave: createApiLeaf<"mutation", typeof import("../functions/projects").leave>(convexApi["projects"]["leave"], { auth: "required", rateLimit: "project/member", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/projects").list>(convexApi["projects"]["list"], { auth: "optional", limit: 20, type: "query" }),
    listForDropdown: createApiLeaf<"query", typeof import("../functions/projects").listForDropdown>(convexApi["projects"]["listForDropdown"], { auth: "required", type: "query" }),
    removeMember: createApiLeaf<"mutation", typeof import("../functions/projects").removeMember>(convexApi["projects"]["removeMember"], { auth: "required", rateLimit: "project/member", type: "mutation" }),
    restore: createApiLeaf<"mutation", typeof import("../functions/projects").restore>(convexApi["projects"]["restore"], { auth: "required", rateLimit: "project/update", type: "mutation" }),
    transfer: createApiLeaf<"mutation", typeof import("../functions/projects").transfer>(convexApi["projects"]["transfer"], { auth: "required", rateLimit: "project/update", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/projects").update>(convexApi["projects"]["update"], { auth: "required", rateLimit: "project/update", type: "mutation" }),
  },
  public: {
    hello: createApiLeaf<"query", typeof import("../functions/public").hello>(convexApi["public"]["hello"], { type: "query" }),
  },
  ratelimitDemo: {
    consumeInteractive: createApiLeaf<"mutation", typeof import("../functions/ratelimitDemo").consumeInteractive>(convexApi["ratelimitDemo"]["consumeInteractive"], { rateLimit: "ratelimit/interactive", type: "mutation" }),
    getInteractiveStatus: createApiLeaf<"query", typeof import("../functions/ratelimitDemo").getInteractiveStatus>(convexApi["ratelimitDemo"]["getInteractiveStatus"], { type: "query" }),
    getSnapshot: createApiLeaf<"query", typeof import("../functions/ratelimitDemo").getSnapshot>(convexApi["ratelimitDemo"]["getSnapshot"], { auth: "required", type: "query" }),
    resetInteractive: createApiLeaf<"mutation", typeof import("../functions/ratelimitDemo").resetInteractive>(convexApi["ratelimitDemo"]["resetInteractive"], { rateLimit: "ratelimit/interactive", type: "mutation" }),
    runCoverage: createApiLeaf<"action", typeof import("../functions/ratelimitDemo").runCoverage>(convexApi["ratelimitDemo"]["runCoverage"], { auth: "required", type: "action" }),
  },
  seed: {
    generateSamples: createApiLeaf<"action", typeof import("../functions/seed").generateSamples>(convexApi["seed"]["generateSamples"], { auth: "required", type: "action" }),
  },
  tags: {
    create: createApiLeaf<"mutation", typeof import("../functions/tags").create>(convexApi["tags"]["create"], { auth: "required", rateLimit: "tag/create", type: "mutation" }),
    deleteTag: createApiLeaf<"mutation", typeof import("../functions/tags").deleteTag>(convexApi["tags"]["deleteTag"], { auth: "required", rateLimit: "tag/delete", type: "mutation" }),
    list: createApiLeaf<"query", typeof import("../functions/tags").list>(convexApi["tags"]["list"], { auth: "required", type: "query" }),
    merge: createApiLeaf<"mutation", typeof import("../functions/tags").merge>(convexApi["tags"]["merge"], { auth: "required", rateLimit: "tag/update", type: "mutation" }),
    popular: createApiLeaf<"query", typeof import("../functions/tags").popular>(convexApi["tags"]["popular"], { auth: "required", type: "query" }),
    update: createApiLeaf<"mutation", typeof import("../functions/tags").update>(convexApi["tags"]["update"], { auth: "required", rateLimit: "tag/update", type: "mutation" }),
  },
  todoComments: {
    addComment: createApiLeaf<"mutation", typeof import("../functions/todoComments").addComment>(convexApi["todoComments"]["addComment"], { auth: "required", rateLimit: "todoComment/create", type: "mutation" }),
    deleteComment: createApiLeaf<"mutation", typeof import("../functions/todoComments").deleteComment>(convexApi["todoComments"]["deleteComment"], { auth: "required", rateLimit: "todoComment/update", type: "mutation" }),
    getCommentThread: createApiLeaf<"query", typeof import("../functions/todoComments").getCommentThread>(convexApi["todoComments"]["getCommentThread"], { type: "query" }),
    getTodoComments: createApiLeaf<"query", typeof import("../functions/todoComments").getTodoComments>(convexApi["todoComments"]["getTodoComments"], { auth: "optional", limit: 20, type: "query" }),
    getUserComments: createApiLeaf<"query", typeof import("../functions/todoComments").getUserComments>(convexApi["todoComments"]["getUserComments"], { auth: "optional", limit: 20, type: "query" }),
    updateComment: createApiLeaf<"mutation", typeof import("../functions/todoComments").updateComment>(convexApi["todoComments"]["updateComment"], { auth: "required", rateLimit: "todoComment/update", type: "mutation" }),
  },
  todos: {
    bulkDelete: createApiLeaf<"mutation", typeof import("../functions/todos").bulkDelete>(convexApi["todos"]["bulkDelete"], { auth: "required", rateLimit: "todo/delete", type: "mutation" }),
    create: createApiLeaf<"mutation", typeof import("../functions/todos").create>(convexApi["todos"]["create"], { auth: "required", rateLimit: "todo/create", type: "mutation" }),
    deleteTodo: createApiLeaf<"mutation", typeof import("../functions/todos").deleteTodo>(convexApi["todos"]["deleteTodo"], { auth: "required", rateLimit: "todo/delete", type: "mutation" }),
    get: createApiLeaf<"query", typeof import("../functions/todos").get>(convexApi["todos"]["get"], { auth: "required", type: "query" }),
    list: createApiLeaf<"query", typeof import("../functions/todos").list>(convexApi["todos"]["list"], { auth: "optional", limit: 20, type: "query" }),
    restore: createApiLeaf<"mutation", typeof import("../functions/todos").restore>(convexApi["todos"]["restore"], { auth: "required", rateLimit: "todo/update", type: "mutation" }),
    search: createApiLeaf<"query", typeof import("../functions/todos").search>(convexApi["todos"]["search"], { auth: "optional", limit: 20, type: "query" }),
    toggleComplete: createApiLeaf<"mutation", typeof import("../functions/todos").toggleComplete>(convexApi["todos"]["toggleComplete"], { auth: "required", rateLimit: "todo/update", type: "mutation" }),
    update: createApiLeaf<"mutation", typeof import("../functions/todos").update>(convexApi["todos"]["update"], { auth: "required", rateLimit: "todo/update", type: "mutation" }),
  },
  triggerDemo: {
    getSnapshot: createApiLeaf<"query", typeof import("../functions/triggerDemo").getSnapshot>(convexApi["triggerDemo"]["getSnapshot"], { auth: "required", type: "query" }),
    runCoverage: createApiLeaf<"mutation", typeof import("../functions/triggerDemo").runCoverage>(convexApi["triggerDemo"]["runCoverage"], { auth: "required", type: "mutation" }),
  },
  user: {
    getCurrentUser: createApiLeaf<"query", typeof import("../functions/user").getCurrentUser>(convexApi["user"]["getCurrentUser"], { auth: "required", type: "query" }),
    getIsAuthenticated: createApiLeaf<"query", typeof import("../functions/user").getIsAuthenticated>(convexApi["user"]["getIsAuthenticated"], { type: "query" }),
    getSessionUser: createApiLeaf<"query", typeof import("../functions/user").getSessionUser>(convexApi["user"]["getSessionUser"], { auth: "optional", type: "query" }),
    updateSettings: createApiLeaf<"mutation", typeof import("../functions/user").updateSettings>(convexApi["user"]["updateSettings"], { auth: "required", type: "mutation" }),
  },
  http: undefined as unknown as typeof httpRouter,
  _http: {
    'examples.allCombinedExample': { path: "/api/examples/items/:id/tags", method: "POST" },
    'examples.inputExample': { path: "/api/examples/items", method: "POST" },
    'examples.paramsExample': { path: "/api/examples/items/:id", method: "GET" },
    'examples.paramsInputExample': { path: "/api/examples/items/:id", method: "PATCH" },
    'examples.paramsSearchParamsExample': { path: "/api/examples/items/:id/history", method: "GET" },
    'examples.redirectExample': { path: "/api/old-path", method: "GET" },
    'examples.searchExample': { path: "/api/examples/search", method: "GET" },
    'examples.uploadExample': { path: "/api/examples/upload", method: "POST" },
    'examples.webhook': { path: "/webhooks/example", method: "POST" },
    health: { path: "/api/health", method: "GET" },
    'todos.create': { path: "/api/todos", method: "POST" },
    'todos.delete': { path: "/api/todos/:id", method: "DELETE" },
    'todos.download': { path: "/api/todos/export/:format", method: "GET" },
    'todos.get': { path: "/api/todos/:id", method: "GET" },
    'todos.list': { path: "/api/todos", method: "GET" },
    'todos.update': { path: "/api/todos/:id", method: "PATCH" },
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

export type TableName = keyof typeof tables;
export type Select<T extends TableName> = InferSelectModel<(typeof tables)[T]>;
export type Insert<T extends TableName> = InferInsertModel<(typeof tables)[T]>;
