// biome-ignore-all format: generated
// This file is auto-generated by better-convex migrate create.
// Do not edit manually.

import { defineMigrationSet } from 'better-convex/orm';

export const migrations = defineMigrationSet([]);
